export type SongType = {
  name: string;
  id: number;
  pst: number;
  t: number;
  ar: { id: number; name: string; tns: undefined[]; alias: undefined[] }[];
  alia: string[];
  pop: number;
  st: number;
  rt: object;
  fee: number;
  v: number;
  crbt: object;
  cf: string;
  al: {
    id: number;
    name: string;
    picUrl: string;
    tns: undefined[];
    pic: number;
  };
  dt: number;
  h: { br: number; fid: number; size: number; vd: number };
  m: { br: number; fid: number; size: number; vd: number };
  l: { br: number; fid: number; size: number; vd: number };
  sq: { br: number; fid: number; size: number; vd: number };
  hr: object;
  a: object;
  cd: string;
  no: number;
  rtUrl: object;
  ftype: number;
  rtUrls: undefined[];
  djId: number;
  copyright: number;
  s_id: number;
  mark: number;
  originCoverType: number;
  originSongSimpleData: object;
  tagPicList: object;
  resourceState: boolean;
  version: number;
  songJumpInfo: object;
  entertainmentTags: object;
  awardTags: object;
  single: number;
  noCopyrightRcmd: object;
  rtype: number;
  rurl: object;
  mst: number;
  cp: number;
  mv: number;
  publishTime: number;
  tns: string[];
};
