export type SongListDetailType = {
  code: number;
  relatedVideos: object;
  playlist: {
    id: number;
    name: string;
    coverImgId: number;
    coverImgUrl: string;
    coverImgId_str: string;
    adType: number;
    userId: number;
    createTime: number;
    status: number;
    opRecommend: boolean;
    highQuality: boolean;
    newImported: boolean;
    updateTime: number;
    trackCount: number;
    specialType: number;
    privacy: number;
    trackUpdateTime: number;
    commentThreadId: string;
    playCount: number;
    trackNumberUpdateTime: number;
    subscribedCount: number;
    cloudTrackCount: number;
    ordered: boolean;
    description: string;
    tags: string[];
    updateFrequency: object;
    backgroundCoverId: number;
    backgroundCoverUrl: object;
    titleImage: number;
    titleImageUrl: object;
    englishTitle: object;
    officialPlaylistType: object;
    copied: boolean;
    relateResType: object;
    subscribers: {
      defaultAvatar: boolean;
      province: number;
      authStatus: number;
      followed: boolean;
      avatarUrl: string;
      accountStatus: number;
      gender: number;
      city: number;
      birthday: number;
      userId: number;
      userType: number;
      nickname: string;
      signature: string;
      description: string;
      detailDescription: string;
      avatarImgId: number;
      backgroundImgId: number;
      backgroundUrl: string;
      authority: number;
      mutual: boolean;
      expertTags: object;
      experts: object;
      djStatus: number;
      vipType: number;
      remarkName: object;
      authenticationTypes: number;
      avatarDetail: object;
      anchor: boolean;
      avatarImgIdStr: string;
      backgroundImgIdStr: string;
      avatarImgId_str: string;
    }[];
    subscribed: boolean;
    creator: {
      defaultAvatar: boolean;
      province: number;
      authStatus: number;
      followed: boolean;
      avatarUrl: string;
      accountStatus: number;
      gender: number;
      city: number;
      birthday: number;
      userId: number;
      userType: number;
      nickname: string;
      signature: string;
      description: string;
      detailDescription: string;
      avatarImgId: number;
      backgroundImgId: number;
      backgroundUrl: string;
      authority: number;
      mutual: boolean;
      expertTags: string[];
      experts: object;
      djStatus: number;
      vipType: number;
      remarkName: object;
      authenticationTypes: number;
      avatarDetail: {
        userType: number;
        identityLevel: number;
        identityIconUrl: string;
      };
      anchor: boolean;
      avatarImgIdStr: string;
      backgroundImgIdStr: string;
      avatarImgId_str: string;
    };
    tracks: [
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: { br: number; fid: number; size: number; vd: number };
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
        tns: string[];
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: undefined[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: object;
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: string;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic_str: string;
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: object;
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
        tns: string[];
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: string;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: object;
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: undefined[];
        pop: number;
        st: number;
        rt: string;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: object;
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: object;
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: object;
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: undefined[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic_str: string;
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: { br: number; fid: number; size: number; vd: number };
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: { br: number; fid: number; size: number; vd: number };
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
        tns: string[];
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic_str: string;
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: { br: number; fid: number; size: number; vd: number };
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
        tns: string[];
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic_str: string;
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: { br: number; fid: number; size: number; vd: number };
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
        tns: string[];
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: { br: number; fid: number; size: number; vd: number };
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
        tns: string[];
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic_str: string;
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: { br: number; fid: number; size: number; vd: number };
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
        tns: string[];
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: string;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic_str: string;
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: { br: number; fid: number; size: number; vd: number };
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
        tns: string[];
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic_str: string;
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: { br: number; fid: number; size: number; vd: number };
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
        tns: string[];
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic_str: string;
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: { br: number; fid: number; size: number; vd: number };
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
        tns: string[];
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic_str: string;
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: { br: number; fid: number; size: number; vd: number };
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
        tns: string[];
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: undefined[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic_str: string;
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: { br: number; fid: number; size: number; vd: number };
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: object;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic_str: string;
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: { br: number; fid: number; size: number; vd: number };
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
      },
      {
        name: string;
        id: number;
        pst: number;
        t: number;
        ar: {
          id: number;
          name: string;
          tns: undefined[];
          alias: undefined[];
        }[];
        alia: string[];
        pop: number;
        st: number;
        rt: string;
        fee: number;
        v: number;
        crbt: object;
        cf: string;
        al: {
          id: number;
          name: string;
          picUrl: string;
          tns: undefined[];
          pic_str: string;
          pic: number;
        };
        dt: number;
        h: { br: number; fid: number; size: number; vd: number };
        m: { br: number; fid: number; size: number; vd: number };
        l: { br: number; fid: number; size: number; vd: number };
        sq: object;
        hr: object;
        a: object;
        cd: string;
        no: number;
        rtUrl: object;
        ftype: number;
        rtUrls: undefined[];
        djId: number;
        copyright: number;
        s_id: number;
        mark: number;
        originCoverType: number;
        originSongSimpleData: object;
        tagPicList: object;
        resourceState: boolean;
        version: number;
        songJumpInfo: object;
        entertainmentTags: object;
        awardTags: object;
        single: number;
        noCopyrightRcmd: object;
        rtype: number;
        rurl: object;
        mst: number;
        cp: number;
        mv: number;
        publishTime: number;
        tns: string[];
      }
    ];
    videoIds: object;
    videos: object;
    trackIds: {
      id: number;
      v: number;
      t: number;
      at: number;
      alg: object;
      uid: number;
      rcmdReason: string;
      sc: object;
      f: object;
      sr: object;
    }[];
    bannedTrackIds: object;
    mvResourceInfos: object;
    shareCount: number;
    commentCount: number;
    remixVideo: object;
    sharedUsers: object;
    historySharedUsers: object;
    gradeStatus: string;
    score: object;
    algTags: string[];
    trialMode: number;
  };
  urls: object;
  privileges: [
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: number;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: number;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: number;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: number;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: number;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    },
    {
      id: number;
      fee: number;
      payed: number;
      realPayed: number;
      st: number;
      pl: number;
      dl: number;
      sp: number;
      cp: number;
      subp: number;
      cs: boolean;
      maxbr: number;
      fl: number;
      pc: object;
      toast: boolean;
      flag: number;
      paidBigBang: boolean;
      preSell: boolean;
      playMaxbr: number;
      downloadMaxbr: number;
      maxBrLevel: string;
      playMaxBrLevel: string;
      downloadMaxBrLevel: string;
      plLevel: string;
      dlLevel: string;
      flLevel: string;
      rscl: object;
      freeTrialPrivilege: {
        resConsumable: boolean;
        userConsumable: boolean;
        listenType: object;
        cannotListenReason: object;
      };
      rightSource: number;
      chargeInfoList: {
        rate: number;
        chargeUrl: object;
        chargeMessage: object;
        chargeType: number;
      }[];
    }
  ];
  sharedPrivilege: object;
  resEntrance: object;
  fromUsers: object;
  fromUserCount: number;
  songFromUsers: object;
};
